Pull Request for Feature validations and model specs
chuaindia/rail-blog-app pull request #3
Opened 2023-01-26 21:18 UTC by chuaindia

In this PR following activities are incorporated : 

- Following validations for the User model are added ---
         The Name must not be blank.
         PostsCounter must be an integer greater than or equal to zero.
- Following validations for the Post model are added ---
         The title must not be blank.
         The title must not exceed 250 characters.
         CommentsCounter must be an integer greater than or equal to zero.
         LikesCounter must be an integer greater than or equal to zero.
- Unit specs for all models' methods and validations are added.

2023-01-26 21:31 UTC, DammyShittu requested changes
Hi @chuaindia,

## Highlights
✔️ Descriptive PR
✔️ Passing linters
✔️ Good branch name

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] Most of your tests are failing. Kindly fix them.

  ![image](https://user-images.githubusercontent.com/54848363/214955110-5dd4b4d7-de2d-4a31-bb5f-dec9ddc5492e.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-27 07:42 UTC, KayLemba requested changes
Hi @chuaindia   👋
Good job so far working on the project requirements!
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight 🎉
No linter errors. ✔️
GitHub flow is followed. ✔️

Required Changes ♻️
Check the comments under the review in the inline comments.
 
Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-01-27 07:42 UTC, KayLemba commented on spec/models/comment_spec.rb
> +    @post = Post.create(AuthorId: subject.id, Title: 'dummy post', Text: 'This is a test for the latest_posts method')
As the previous code reviewer suggested kindly fix your tests. Whenever I try running your tests Im getting the error below.

![test](https://user-images.githubusercontent.com/79506105/215033102-b062d006-5031-4e23-b831-4d10f7a61a64.PNG)

2023-01-28 19:52 UTC, Ismailco requested changes
### Hi @chuaindia, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


 ## Highlights

✔️  No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-28 19:52 UTC, Ismailco commented on spec/models/user_spec.rb
> +  it 'Has a latest_posts method' do
- [ ] As the previous reviewer mentioned kindly make sure to fix these errors so the rspec tests are passing 👇🏼 
![Screenshot_20230128_204722](https://user-images.githubusercontent.com/25227022/215287904-4f6065f6-82b9-454c-9a52-f04e521cf285.png)

2023-01-28 19:52 UTC, Ismailco commented on spec/models/post_spec.rb
> +  end
- [ ] As the previous reviewer mentioned kindly make sure to fix these errors so the rspec tests are passing 👇🏼 
![Screenshot_20230128_204700](https://user-images.githubusercontent.com/25227022/215287931-b297c047-f49f-4207-a5ac-7f4ddab7a0ae.png)

2023-01-28 19:52 UTC, Ismailco commented on spec/models/like_spec.rb
> +  end
- [ ] As the previous reviewer mentioned kindly make sure to fix these errors so the rspec tests are passing 👇🏼 
![Screenshot_20230128_204641](https://user-images.githubusercontent.com/25227022/215287944-388dc438-b606-40e3-8ca3-3875f7f5b1a1.png)

2023-01-28 19:52 UTC, Ismailco commented on spec/models/comment_spec.rb
> +    expect(text).to eq('Unit test for the method of most_recent_comments')
- [ ] As the previous reviewer mentioned kindly make sure to fix these errors so the rspec tests are passing 👇🏼 
![Screenshot_20230128_204624](https://user-images.githubusercontent.com/25227022/215287956-d83788be-3336-4634-b623-aee77d89bb86.png)

2023-01-28 21:20 UTC, Nemwel-Boniface requested changes
## Hello @chuaindia    :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

Great job addressing some of the changes that were requested by a previous reviewer :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)
## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

I tried reaching out to you via slack but unfortunately, you were not there.

_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-28 21:20 UTC, Nemwel-Boniface commented on spec/models/post_spec.rb
> +  end
- [ ] Unfortunately, this tests still fail on my end despite you making the changes requested by the previous reviewers. Kindly look into why this is the case

![image](https://user-images.githubusercontent.com/86318284/215291492-ab77ded7-47fb-424b-9608-a68d67db3e24.png)

2023-01-28 21:20 UTC, Nemwel-Boniface commented on spec/models/user_spec.rb
> +  end
- [ ] Unfortunately, this tests still fail on my end despite you making the changes requested by the previous reviewers. Kindly look into why this is the case

![image](https://user-images.githubusercontent.com/86318284/215291536-dd270431-1585-4940-84a6-6fa5642d0c36.png)

2023-01-28 21:20 UTC, Nemwel-Boniface commented on spec/models/user_spec.rb
> +  end
- [ ] Unfortunately, this tests still fail on my end despite you making the changes requested by the previous reviewers. Kindly look into why this is the case

![image](https://user-images.githubusercontent.com/86318284/215291542-0737577d-6fd4-4427-b8ad-14e1dde6ec5f.png)

2023-01-29 03:30 UTC, chuaindia commented
I don't understand this part ..... I  am unable to come out of this error
.... Probably because of my device ..... The active load error or something
.... I am really faded up regarding the db:migrate ...... Probably the
postgresql is not working ..... I googled a lot but problem can not be
solved .....
Feeling really fustrated that how this error prevails how I can continue my
work ,....
Tanusri

On Sun, 29 Jan 2023, 02:50 Nemwel Boniface, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> Hello @chuaindia <https://github.com/chuaindia> 👋 ,
>
> I'm Nemwel your reviewer for this PR 🧔‍♂️
>
> Great job addressing some of the changes that were requested by a previous
> reviewer 👏
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
>
>
> <https://camo.githubusercontent.com/4f9601b422a77702aefe8e13485d2d5618cc0c30772eb2aa9f4129eac4757e06/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4b7942657366386b4e5436733838534567622f67697068792e676966>
> Highlights
>
> Great job setting up the correct linters ✔️
> Professional documentation ✔️
> Correct workflow ✔️
> Meaningful commit messages ✔️
> ♻️ Required Changes ♻️
>
> I tried reaching out to you via slack but unfortunately, you were not
> there.
>
> *Check the comments under the review.*
> [Optional] suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding! 🥳 👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me ***@***.***
> <https://github.com/Nemwel-Boniface>* in your question so I can receive
> the notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In spec/models/post_spec.rb
> <https://github.com/chuaindia/rail-blog-app/pull/3#discussion_r1089815749>
> :
>
> > +  it 'should test for integers greater than 0' do
>
> +    subject.CommentCounter = 11
>
> +    expect(subject.comments_counter).to eql 11
>
> +  end
>
> +
>
> +  it 'should respond to recent_five_comments method' do
>
> +    expect(subject).to respond_to(:latest_comments)
>
> +  end
>
>
>
>    - Unfortunately, this tests still fail on my end despite you making
>    the changes requested by the previous reviewers. Kindly look into why this
>    is the case
>
> [image: image]
> <https://user-images.githubusercontent.com/86318284/215291492-ab77ded7-47fb-424b-9608-a68d67db3e24.png>
> ------------------------------
>
> In spec/models/user_spec.rb
> <https://github.com/chuaindia/rail-blog-app/pull/3#discussion_r1089815899>
> :
>
> > +  it 'should respond to recent_three_posts method' do
>
> +    expect(subject).to respond_to(:latest_posts)
>
> +  end
>
>
>
>    - Unfortunately, this tests still fail on my end despite you making
>    the changes requested by the previous reviewers. Kindly look into why this
>    is the case
>
> [image: image]
> <https://user-images.githubusercontent.com/86318284/215291536-dd270431-1585-4940-84a6-6fa5642d0c36.png>
> ------------------------------
>
> In spec/models/user_spec.rb
> <https://github.com/chuaindia/rail-blog-app/pull/3#discussion_r1089815904>
> :
>
> > +  it 'should test for presence of name' do
>
> +    subject.Name = nil
>
> +    expect(subject).to_not be_valid
>
> +  end
>
> +
>
> +  it 'should test for empty name' do
>
> +    subject.Name = ''
>
> +    expect(subject).to_not be_valid
>
> +  end
>
> +
>
> +  it 'should test for integer' do
>
> +    subject.PostCounter = 'a'
>
> +    expect(subject).to_not be_valid
>
> +  end
>
> +
>
> +  it 'should test for integers lesser than 0' do
>
> +    subject.PostCounter = -1
>
> +    expect(subject).to_not be_valid
>
> +  end
>
>
>
>    - Unfortunately, this tests still fail on my end despite you making
>    the changes requested by the previous reviewers. Kindly look into why this
>    is the case
>
> [image: image]
> <https://user-images.githubusercontent.com/86318284/215291542-0737577d-6fd4-4427-b8ad-14e1dde6ec5f.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/chuaindia/rail-blog-app/pull/3#pullrequestreview-1274024049>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZPANHJBMYT3CJUNXAFQTEDWUWESHANCNFSM6AAAAAAUH7EI6I>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-30 21:16 UTC, merged